version: '3.8'

services:
  slidesage:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../input:/app/input
      - ../output:/app/output
    environment:
      - OLLAMA_HOST=ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve

volumes:
  ollama_data: 